#!/bin/sh

#cmd="java -cp build/fop.jar:lib/batik-all-1.6.jar:lib/xalan-2.7.0.jar:lib/commons-io-1.3.1.jar:lib/commons-logging-1.0.4.jar:lib/avalon-framework-4.2.0.jar:lib/xml-apis-1.3.02.jar:lib/serializer-2.7.0.jar:lib/xercesImpl-2.7.1.jar org.apache.fop.fonts.apps.TTFReader"

cmd="fop-ttfreader"
dir="."
ext=".xml"

for f in `ls -1 $dir | grep '\.ttf$'`;
do
	echo "processing file : $dir/$f"
	fname=`echo $f | cut -d . -f1`
	newf="$dir/$fname$ext"
	if ${cmd} $dir/$f $newf
	then echo "writing to file $newf : success"
	else break
	fi
done

